name: Update Release

on:
    push:
      paths:
        - maw-muter_AHK/maw-muter.ahk
    workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest release
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput('release_id', latestRelease.data.id);

      - name: Update .ahk file in the release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const release_id = core.getInput('release_id');
            const file_path = path.join(process.env.GITHUB_WORKSPACE, 'maw-muter_AHK', 'maw-muter.ahk');
            const content = fs.readFileSync(file_path);

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release_id,
              name: 'maw-muter.ahk',
              data: content,
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': content.length
              }
            });

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
